name: magicslides_app
description: A Flutter app for generating presentations using MagicSlides API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^24.1.41
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  open_file: ^3.3.2
  http: ^1.1.2
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  dropdown_button2: ^2.3.9
  intl: ^0.18.1
  url_launcher: ^6.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
